version: "3.8"

services:
  app:  ## service name
    container_name: good-container
    build:
      context: .
      dockerfile: Dockerfile-app
    environment:
      - TZ=Asia/Seoul
    ports:
      - 9999:8080
    depends_on:
      - database
  
  database:  ## service name
    container_name: good-db
    build:
      context: .
      dockerfile: Dockerfile-db
#    image: mysql:8.0
    hostname: docker-mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: ver4
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: 1111
      